### ISSUE TITLE
Failed to invoke as js transform plugin

### ISSUE THREAD

**Issue by sebinsua** [JiangWeixian/vite-plugin-barrel#10]
I get this error message when I try to use it on my Ubuntu machine:

```
❯ yarn build
vite v5.1.1 building for production...
transforming (1) index.htmlthread '<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.42/src/impls/core/mod.rs:266:67:
called `Result::unwrap()` on an `Err` value: LayoutError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'thread '<unnamed>' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.273.5/src/plugin.rs:162:14:
failed to invoke plugin: failed to invoke plugin on 'None'

Caused by:
    0: failed to invoke `/home/username/dev/projectname/node_modules/swc-plugin-barrel/swc_plugin_barrel.wasm` as js transform plugin at /home/username/dev/projectname/node_modules/swc-plugin-barrel/swc_plugin_barrel.wasm
    1: RuntimeError: unreachable
           at __rust_start_panic (<module>[1545]:0x1caf3c)
           at rust_panic (<module>[1536]:0x1cacf4)
           at std::panicking::rust_panic_with_hook::h01fa6d9286535f9c (<module>[1535]:0x1cac27)
           at std::panicking::begin_panic_handler::{{closure}}::h322b08995dd5f5cc (<module>[1523]:0x1c9fdf)
           at std::sys_common::backtrace::__rust_end_short_backtrace::hd7b53dba62f7f0aa (<module>[1522]:0x1c9f02)
           at rust_begin_unwind (<module>[1530]:0x1ca5de)
           at core::panicking::panic_fmt::h2a1cf3beec13dfc3 (<module>[1618]:0x1cffc8)
           at core::result::unwrap_failed::hd8d94c2109be2ae4 (<module>[1650]:0x1d642e)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h48424417eaf07b77 (<module>[378]:0x923c4)
           at swc_ecma_ast::expr::_::<impl rkyv::Deserialize<swc_ecma_ast::expr::Expr,__D> for <swc_ecma_ast::expr::Expr as rkyv::Archive>::Archived>::deserialize::h5f6fee43ff97b42c (<module>[631]:0xf7c82)
           at swc_ecma_ast::expr::_::<impl rkyv::Deserialize<swc_ecma_ast::expr::Expr,__D> for <swc_ecma_ast::expr::Expr as rkyv::Archive>::Archived>::deserialize::h5f6fee43ff97b42c (<module>[631]:0xf74e2)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h325b06055c61d1a1 (<module>[668]:0x108852)
           at rkyv::impls::alloc::boxed::<impl rkyv::Deserialize<alloc::boxed::Box<T>,D> for rkyv::boxed::ArchivedBox<<T as rkyv::ArchiveUnsized>::Archived>>::deserialize::hbfd6c626095a8b4f (<module>[170]:0x40d8a)
           at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h3ee3164ddab84063 (<module>[161]:0x3ee86)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::ha86c68fafd29bb58 (<module>[166]:0x4089a)
           at rkyv::impls::alloc::boxed::<impl rkyv::Deserialize<alloc::boxed::Box<T>,D> for rkyv::boxed::ArchivedBox<<T as rkyv::ArchiveUnsized>::Archived>>::deserialize::ha9aa674da9ba4155 (<module>[48]:0x1678f)
           at swc_ecma_ast::expr::_::<impl rkyv::Deserialize<swc_ecma_ast::expr::Expr,__D> for <swc_ecma_ast::expr::Expr as rkyv::Archive>::Archived>::deserialize::h5f6fee43ff97b42c (<module>[40]:0xb09a)
           at swc_ecma_ast::expr::_::<impl rkyv::Deserialize<swc_ecma_ast::expr::Expr,__D> for <swc_ecma_ast::expr::Expr as rkyv::Archive>::Archived>::deserialize::h5f6fee43ff97b42c (<module>[40]:0xbe2f)
           at swc_ecma_ast::expr::_::<impl rkyv::Deserialize<swc_ecma_ast::expr::Expr,__D> for <swc_ecma_ast::expr::Expr as rkyv::Archive>::Archived>::deserialize::h5f6fee43ff97b42c (<module>[40]:0xcdd8)
           at rkyv::impls::alloc::boxed::<impl rkyv::Deserialize<alloc::boxed::Box<T>,D> for rkyv::boxed::ArchivedBox<<T as rkyv::ArchiveUnsized>::Archived>>::deserialize::hef3afda35c40e28c (<module>[59]:0x1c6c5)
           at swc_ecma_ast::expr::_::<impl rkyv::Deserialize<swc_ecma_ast::expr::Expr,__D> for <swc_ecma_ast::expr::Expr as rkyv::Archive>::Archived>::deserialize::h5f6fee43ff97b42c (<module>[40]:0xb4dc)
           at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h3ee3164ddab84063 (<module>[75]:0x20d79)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h7119f499e4fe9713 (<module>[25]:0x614a)
           at swc_common::plugin::serialized::PluginSerializedBytes::deserialize::h8827830fd868d0e6 (<module>[1017]:0x183f72)
           at __transform_plugin_process_impl (<module>[989]:0x17d6cd)
           at __transform_plugin_process_impl.command_export (<module>[1716]:0x1db18c)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.42/src/impls/core/mod.rs:266:67:
called `Result::unwrap()` on an `Err` value: LayoutError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.273.5/src/plugin.rs:162:14:
failed to invoke plugin: failed to invoke plugin on 'None'

Caused by:
    0: failed to invoke `/home/username/dev/projectname/node_modules/swc-plugin-barrel/swc_plugin_barrel.wasm` as js transform plugin at /home/username/dev/projectname/node_modules/swc-plugin-barrel/swc_plugin_barrel.wasm
    1: RuntimeError: unreachable
           at __rust_start_panic (<module>[1545]:0x1caf3c)
           at rust_panic (<module>[1536]:0x1cacf4)
           at std::panicking::rust_panic_with_hook::h01fa6d9286535f9c (<module>[1535]:0x1cac27)
           at std::panicking::begin_panic_handler::{{closure}}::h322b08995dd5f5cc (<module>[1523]:0x1c9fdf)
           at std::sys_common::backtrace::__rust_end_short_backtrace::hd7b53dba62f7f0aa (<module>[1522]:0x1c9f02)
           at rust_begin_unwind (<module>[1530]:0x1ca5de)
           at core::panicking::panic_fmt::h2a1cf3beec13dfc3 (<module>[1618]:0x1cffc8)
           at core::result::unwrap_failed::hd8d94c2109be2ae4 (<module>[1650]:0x1d642e)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h48424417eaf07b77 (<module>[378]:0x923c4)
           at swc_ecma_ast::expr::_::<impl rkyv::Deserialize<swc_ecma_ast::expr::Expr,__D> for <swc_ecma_ast::expr::Expr as rkyv::Archive>::Archived>::deserialize::h5f6fee43ff97b42c (<module>[631]:0xf7c82)
           at swc_ecma_ast::expr::_::<impl rkyv::Deserialize<swc_ecma_ast::expr::Expr,__D> for <swc_ecma_ast::expr::Expr as rkyv::Archive>::Archived>::deserialize::h5f6fee43ff97b42c (<module>[631]:0xf7065)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h325b06055c61d1a1 (<module>[668]:0x108852)
           at swc_ecma_ast::decl::_::<impl rkyv::Deserialize<swc_ecma_ast::decl::Decl,__D> for <swc_ecma_ast::decl::Decl as rkyv::Archive>::Archived>::deserialize::h9f5ed8b4f1f9895a (<module>[46]:0x150f1)
           at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h3ee3164ddab84063 (<module>[75]:0x211f6)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h7119f499e4fe9713 (<module>[25]:0x614a)
           at swc_common::plugin::serialized::PluginSerializedBytes::deserialize::h8827830fd868d0e6 (<module>[1017]:0x183f72)
           at __transform_plugin_process_impl (<module>[989]:0x17d6cd)
           at __transform_plugin_process_impl.command_export (<module>[1716]:0x1db18c)
✓ 1 modules transformed.
error during build:
Error: [vite-plugin-barrel:transform] failed to handle: failed to invoke plugin: failed to invoke plugin on 'None'

Caused by:
    0: failed to invoke `/home/username/dev/projectname/node_modules/swc-plugin-barrel/swc_plugin_barrel.wasm` as js transform plugin at /home/username/dev/projectname/node_modules/swc-plugin-barrel/swc_plugin_barrel.wasm
    1: RuntimeError: unreachable
           at __rust_start_panic (<module>[1545]:0x1caf3c)
           at rust_panic (<module>[1536]:0x1cacf4)
           at std::panicking::rust_panic_with_hook::h01fa6d9286535f9c (<module>[1535]:0x1cac27)
           at std::panicking::begin_panic_handler::{{closure}}::h322b08995dd5f5cc (<module>[1523]:0x1c9fdf)
           at std::sys_common::backtrace::__rust_end_short_backtrace::hd7b53dba62f7f0aa (<module>[1522]:0x1c9f02)
           at rust_begin_unwind (<module>[1530]:0x1ca5de)
           at core::panicking::panic_fmt::h2a1cf3beec13dfc3 (<module>[1618]:0x1cffc8)
           at core::result::unwrap_failed::hd8d94c2109be2ae4 (<module>[1650]:0x1d642e)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h48424417eaf07b77 (<module>[378]:0x923c4)
           at swc_ecma_ast::expr::_::<impl rkyv::Deserialize<swc_ecma_ast::expr::Expr,__D> for <swc_ecma_ast::expr::Expr as rkyv::Archive>::Archived>::deserialize::h5f6fee43ff97b42c (<module>[631]:0xf7c82)
           at swc_ecma_ast::expr::_::<impl rkyv::Deserialize<swc_ecma_ast::expr::Expr,__D> for <swc_ecma_ast::expr::Expr as rkyv::Archive>::Archived>::deserialize::h5f6fee43ff97b42c (<module>[631]:0xf74e2)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h325b06055c61d1a1 (<module>[668]:0x108852)
           at rkyv::impls::alloc::boxed::<impl rkyv::Deserialize<alloc::boxed::Box<T>,D> for rkyv::boxed::ArchivedBox<<T as rkyv::ArchiveUnsized>::Archived>>::deserialize::hbfd6c626095a8b4f (<module>[170]:0x40d8a)
           at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h3ee3164ddab84063 (<module>[161]:0x3ee86)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::ha86c68fafd29bb58 (<module>[166]:0x4089a)
           at rkyv::impls::alloc::boxed::<impl rkyv::Deserialize<alloc::boxed::Box<T>,D> for rkyv::boxed::ArchivedBox<<T as rkyv::ArchiveUnsized>::Archived>>::deserialize::ha9aa674da9ba4155 (<module>[48]:0x1678f)
           at swc_ecma_ast::expr::_::<impl rkyv::Deserialize<swc_ecma_ast::expr::Expr,__D> for <swc_ecma_ast::expr::Expr as rkyv::Archive>::Archived>::deserialize::h5f6fee43ff97b42c (<module>[40]:0xb09a)
           at swc_ecma_ast::expr::_::<impl rkyv::Deserialize<swc_ecma_ast::expr::Expr,__D> for <swc_ecma_ast::expr::Expr as rkyv::Archive>::Archived>::deserialize::h5f6fee43ff97b42c (<module>[40]:0xbe2f)
           at swc_ecma_ast::expr::_::<impl rkyv::Deserialize<swc_ecma_ast::expr::Expr,__D> for <swc_ecma_ast::expr::Expr as rkyv::Archive>::Archived>::deserialize::h5f6fee43ff97b42c (<module>[40]:0xcdd8)
           at rkyv::impls::alloc::boxed::<impl rkyv::Deserialize<alloc::boxed::Box<T>,D> for rkyv::boxed::ArchivedBox<<T as rkyv::ArchiveUnsized>::Archived>>::deserialize::hef3afda35c40e28c (<module>[59]:0x1c6c5)
           at swc_ecma_ast::expr::_::<impl rkyv::Deserialize<swc_ecma_ast::expr::Expr,__D> for <swc_ecma_ast::expr::Expr as rkyv::Archive>::Archived>::deserialize::h5f6fee43ff97b42c (<module>[40]:0xb4dc)
           at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h3ee3164ddab84063 (<module>[75]:0x20d79)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h7119f499e4fe9713 (<module>[25]:0x614a)
           at swc_common::plugin::serialized::PluginSerializedBytes::deserialize::h8827830fd868d0e6 (<module>[1017]:0x183f72)
           at __transform_plugin_process_impl (<module>[989]:0x17d6cd)
           at __transform_plugin_process_impl.command_export (<module>[1716]:0x1db18c)
file: vite/modulepreload-polyfill.js
```

**Comment by JiangWeixian** [comment]
what kind of `@swc/core` version do you use?

**Comment by JiangWeixian** [comment]
can you provide mini repo?

**Comment by lauri865** [comment]
Same issue with Vite5 + @vitejs/plugin-react-swc + @swc/core@1.6.5

**Comment by lauri865** [comment]
Got it to work by forcing @swc/core to resolve to version 1.3.105.

However, while this plugin reduces the amount of files to be transformed quite significantly, it also makes the build process 50% slower on an M2Pro Macbook, unfortunately.

**Comment by JiangWeixian** [comment]
@lauri865 v0.2.0 use oxc_resolver optimize performace issue, maybe much better, you can try it

**Comment by gustaff-weldon** [comment]
@JiangWeixian I have tried 0.2 with simple config:
```
    react({
      plugins: [swc_plugin_barrel()]
    }),
    barrel(),
```

and getting a similar error

Env:
"@vitejs/plugin-react-swc": "^3.7.1",
    "vite": "^5.4.11",
    "vite-plugin-barrel": "^0.2.0",

**Comment by JiangWeixian** [comment]
this issue should be fixed, according to swc docs, `swc_core` version should match `@swc/core` version. Within `swc-plugin-barrel@0.1.x - 0.2.x` and `vite-plugin-barrel@0.2.x - 0.3.x`, it use `swc_core@0.96.5`, should use `@swc/core@1.6.x`

![CleanShot 2024-12-25 at 20 55 49@2x](https://github.com/user-attachments/assets/859225e0-52e7-4a70-96ab-d58279d2ac37)

https://swc.rs/docs/plugin/selecting-swc-core

if meet this issue again, feel free to reopen it
